name: Deploy To GCP

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  build_publish_deploy:
    if: ${{ github.event.pull_request.merged }}
    name: Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
        export_default_credentials: true
    
    - name: Google Authorization
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
         
    - name: Configure Docker
      run: |
        gcloud auth configure-docker
    
    - name: Build & Publish
      run: |
        gcloud config set project ${{ secrets.GCP_PROJ_ID }}
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJ_ID }}/${{ secrets.GCP_APPLICATION }}
        gcloud config set run/region us-central1
      
    - name: Deploy
      run: |
        gcloud run deploy ${{ secrets.GCP_APPLICATION }} --image gcr.io/${{ secrets.GCP_PROJ_ID }}/${{ secrets.GCP_APPLICATION }} \
        --platform managed \
        --allow-unauthenticated \
        --memory 512M
